name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm i

      - name: Run app
        run: npm run start:test & npx wait-on http://localhost:3000

      - name: Run tests
        run: npx cypress run

      - name: Enforce Coverage
        run: npx nyc check-coverage --lines 75
